// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewInventory struct {
	Name string `json:"name"`
}

type NewInventoryItem struct {
	Quantity    int `json:"quantity"`
	InventoryID int `json:"inventoryId"`
	ItemID      int `json:"itemId"`
}

type NewItem struct {
	Name string `json:"name"`
}
