// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewInventory struct {
	Name string `json:"name"`
}

type NewInventoryItem struct {
	Quantity    int    `json:"quantity"`
	InventoryID string `json:"inventoryId"`
	ItemID      string `json:"itemId"`
}

type NewItem struct {
	Name string `json:"name"`
}

type NewUser struct {
	FirstName            string `json:"firstName"`
	LastName             string `json:"lastName"`
	Email                string `json:"email"`
	Passord              string `json:"passord"`
	ConfirmationPassword string `json:"confirmationPassword"`
}
